import Head from "next/head";
import { GetServerSideProps } from "next";

type Props = {
  random: number;
};

const Ssr = (props: Props) => {
  return (
    <div className="main">
      <Head>
        <title>SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        SSRで生成されたページです。
        <br />
        <em>{props.random}</em>
      </p>
    </div>
  );
}

export default Ssr;

// サーバサイドで実行する処理(getServerSideProps)を定義する
export const getServerSideProps: GetServerSideProps = async (context) => {
  // APIやDBからのデータ取得処理などを記載
  const random = Math.floor(Math.random() * 100);

  return {
    props: {
      random,
    },
  };
};
